export const routes = Object.freeze({
  HOME_SCREEN: "HomeScreen",
  TOPPROF_SCREEN: "TopprofScreen",
  LOGIN_SCREEN: "LoginScreen",
  MENU_SCREEN: "MenuScreen",
  OFFERS_SCREEN: "OffersScreen",
  OTP_SCREEN: "OTPScreen",
  PROFILE_SCREEN: "ProfileScreen",
  PROFILEWATCH_SCREEN: "ProfilewatchScreen",
  RESET_PASSWORD: "ResetPassword",
  RESET_PASSWORD_SCREEN: "ResetPasswordScreen",
  SETTINGS_SCREEN: "SettingsScreen",
  SIGNUP_SCREEN: "SignUpScreen",
  SPLASH_SCREEN: "SplashScreen",
  WELCOME_SCREEN: "WelcomeScreen",
});
